### PR TITLE
Optimize parser by a Zillion %

### PR DESCRIPTION
**Pull request by hugopl**
The main problem was repeated allocations when consuming characters by doing

```Crystal
@buffer += @str[@i]
```

So to parse the string `abc` we allocated `a`, then `ab`, then `abc`.

Now the code just store the string indexes and use them when necessary. So a 400kb file that was taking more than a hour to render now render in milliseconds.

Tested with a plain text file with 200kb then with a 2Mb file got the results:

```
$ ./parser foo/sample3.txt
rendering foo/sample3.txt
  0.005337   0.000000   0.005337 (  0.005346)
$ ./parser foo/sample-2mb-text-file.txt
rendering foo/sample-2mb-text-file.txt
  0.057601   0.000000   0.057601 (  0.057687)
$ ls -lah foo/
Permissions Size User Date Modified Name
.rw-r--r--   202 hugo 25 nov 14:57  parser.cr
.rw-r--r--  2,2M hugo 25 nov 14:55  sample-2mb-text-file.txt
.rw-r--r--  177k hugo 25 nov 14:55  sample3.txt
```

Test env:
 - ArchLinux
 - Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 - 16Gb RAM
 - Some Sata SSD hard drive
 - Crystal 1.6.2
 - LLVM: 14.0.6

### CODE REVIEW

**Review by setanta — APPROVED** [review]

**Review by setanta — APPROVED** [review]
:+1:

**Comment by robacarp** [comment]
This is quite the optimization. I have two questions.

First, this change makes the code far less obvious to the reader that's not familiar with the code. The consequence of this is that later bugs are less likely to be found and fixed by any arbitrary community member. Perhaps that's the problem domain at play. However, I wonder if it would be possible to use a String::Builder class instead? I think it uses a similar algorithm behind the scenes. Would that make it easier to read?

Second, with any performance related pull request, I would like to see a before and after comparison. Ideally we would have performance specs built into CI so an easy comparison could be made. In lieu of that, would you please provide a before and after measurement? Crystal provides a nice [Benchmark](https://crystal-lang.org/api/1.2.2/Benchmark.html) class which runs the simulation multiple times and performs the statistics automatically.

**Comment by hugopl** [comment]
Hi,

Yes, more optimized code are most of the time a bit harder for the eyes, that's the price.

BTW I guess I did something wrong with the first results (I guess I forgot to recompile the benchmark and measured the speed of a lexer I was doing as experiment :sweat_smile: )

But here the results of parsing the 345kb file of `Int8.html` file from Crystal docs.

**Current master branch**
```
$ ./parser-test /usr/share/doc/crystal/api/Int8.html 
  6.520321   0.026642   6.546963 (  6.550224)
$ ./parser-test /usr/share/doc/crystal/api/Int8.html 
  6.015328   0.012993   6.028321 (  6.031401)
$ ./parser-test /usr/share/doc/crystal/api/Int8.html 
  5.987136   0.016721   6.003857 (  6.007143)
```

**This PR**
```
$ ./parser-test /usr/share/doc/crystal/api/Int8.html 
  0.004232   0.000000   0.004232 (  0.004239)
$ ./parser-test /usr/share/doc/crystal/api/Int8.html 
  0.004174   0.000000   0.004174 (  0.004179)
$ ./parser-test /usr/share/doc/crystal/api/Int8.html 
  0.004277   0.000000   0.004277 (  0.004282)
```

**Benchmark code**
```Crystal
require "benchmark"
require "./src/liquid"

filename = ARGV[0]
contents = File.read(filename)

time = Benchmark.measure do
  Liquid::Template.parse(contents)
end

 puts time
```

The file used as template in the benchmark has no liquid tags at all, in production I need to render 400kb files and the Crystal version of liquid still *a lot* slower than the Ruby version even with this optimization... my guess is the over used of `String#[]` that's causing the slowness, I have a branch that reads the string using `Char::Reader`, however I noticed that the Ruby version of liquid does the entire tokenization just using regexes (what explain liquid not support things like `{{ "}}" }}`), maybe this is the way to go... but it would require I rewrite of the Parser class.

**Benchmark Env**
ArchLinux, Crystal 1.6.2, LLVM 14.0.6, AMD Ryzen 9 5900X 12-Core Processor, 32G RAM

**Comment by hugopl** [comment]
> I wonder if it would be possible to use a String::Builder class instead? I think it uses a similar algorithm behind the scenes. Would that make it easier to read?

`String::Builder` allocates an initial buffer then calls `realloc` when the buffer is full and more data is written, so it would be faster than the current code in master due to the larges initial and reallocated buffers, however slower than this PR approach that does no `realloc` calls at all.

**Comment by robacarp** [comment]
This is the comparison I was thinking of:

```crystal
require "./liquid"
require "benchmark"

file = File.read("int8.html")

Benchmark.ips do |x|
  x.report("classic parser") { Liquid::Parser.parse file }
  x.report("buffered parser") { Liquid::BufferedParser.parse file }
  x.report("builder parser") { Liquid::BuilderParser.parse file }
end
```

```
> crystal run --release src/parser_benchmark.crcrystal run --release src/parser_benchmark.cr
 classic parser 159.90m (  6.25s ) (± 0.00%)  64.5GB/op  1925.13× slower
buffered parser 307.83  (  3.25ms) (± 0.53%)    319B/op          fastest
 builder parser 225.35  (  4.44ms) (± 0.51%)   1.0MB/op     1.37× slower
```

I confess I don't really know enough about liquid to say that I understand this parser code. Parser code is often difficult to write in a way that's not spaghetti, perhaps this is expected. Reading through it made me confident that I don't want to be responsible to modify it regardless of this change. 

I made a variant of the parser based on String::Builder and it is a tad slower than what you have here. I'm not at all confident that it's correct. Were the parser code readable in the first place I would say it's worth the minor penalty to encourage readability. A trade off or 1ms over a 365k file is _fine_ with me, though it is indeed slower.

<details>
  <summary>Here is my String::Builder based parser</summary>
  <code><pre>

require "./blocks"

module Liquid
  class BuilderParser
    STATEMENT        = /^\s*(?<keyword>[a-z]+).*$/
    ENDRAW_STATEMENT = {
      "raw"     => /(?<!\\){%\s*endraw\s*\-?%}|$/,
      "comment" => /(?<!\\){%\s*endcomment\s*\-?%}|$/,
    }

    getter root : Root

    @str : String
    @i = 0
    @current_line = 0
    @escape = false
    @lstrip = false
    @rstrip = false

    # buffers
    @nodes = Array(Node).new

    def reset_buffer
      @buffer = String::Builder.new
    end

    def string_buffer
      @buffer.to_s
    end

    def self.parse(str : String)
      internal = self.new str
      internal.parse
      Template.new internal.root
    end

    def self.parse(file : File)
      str = file.gets_to_end
      path = File.dirname(file.path)

      internal = self.new str
      internal.parse
      Template.new internal.root, path
    end

    def initialize(@str)
      @root = Root.new
      @nodes << @root
      @buffer = String::Builder.new
    end

    def has_char?
      @i < str.size
    end

    # parse string
    def parse
      @i = 0
      while @i < @str.size - 1
        if @str[@i] == '{' && @str[@i + 1] == '%' && !@escape
          @i += 2
          if @str[@i] == '-'
            @rstrip = true
            @i += 1
          end
          add_raw
          consume_statement
        elsif @str[@i] == '{' && @str[@i + 1] == '{' && !@escape
          @i += 2
          if @str[@i] == '-'
            @rstrip = true
            @i += 1
          end
          add_raw
          consume_expression
        else
          consume_char
        end
        @escape = false if @escape
        @escape = true if @str[@i] == '\\'
        @i += 1
      end
      consume_char # last char ?
      add_raw
    end

    # Create and add a Raw node with current buffer
    def add_raw
      if !@buffer.empty?
        rendered = string_buffer
        rendered = rendered.lstrip if @lstrip
        rendered = rendered.rstrip if @rstrip
        @nodes.last << Block::Raw.new rendered
        reset_buffer
      end
      @lstrip = false
      @rstrip = false
    end

    def consume_expression
      while @i < @str.size - 1
        if @str[@i] == '-' && @str[@i + 1] == '}' && @str[@i + 2] == '}'
          @lstrip = true
          @i += 2
          break
        elsif @str[@i] == '}' && @str[@i + 1] == '}'
          @i += 1
          break
        else
          consume_char
        end
        @i += 1
      end

      if !@buffer.empty?
        @nodes.last << Expression.new string_buffer
        reset_buffer
      else
        raise "Invalid Expression at line #{@current_line}"
      end
    end

    # Consume a statement
    def consume_statement
      while @i < @str.size - 1
        if @str[@i] == '-' && @str[@i + 1] == '%' && @str[@i + 2] == '}'
          @lstrip = true
          @i += 2
          break
        elsif @str[@i] == '%' && @str[@i + 1] == '}'
          @i += 1
          break
        else
          consume_char
        end
        @i += 1
      end

      if match = string_buffer.match STATEMENT
        block_class = BlockRegister.for_name match["keyword"]
        case block_class.type
        when BlockType::End
          while (pop = @nodes.pop?) && pop.is_a? Block && !pop.class.type == BlockType::Begin
          end
        when BlockType::Begin
          block = block_class.new string_buffer
          @nodes.last << block
          @nodes << block
        when BlockType::Inline
          @nodes.last << block_class.new string_buffer
        else # when BlockType::Raw, BlockType::RawHidden
          if match = @str.match(ENDRAW_STATEMENT[match["keyword"]], @i)
            j = match.begin.not_nil! - 1
            @buffer << @str[@i + 1..j]
            @i = match.end.not_nil! - 1
            @nodes.last << block_class.new string_buffer
          end
        end
      else
        raise "Invalid Statement at line #{@current_line}"
      end

      reset_buffer
    end

    # Add current char to buffer
    def consume_char
      if @i < @str.size
        @buffer << @str[@i]
        @current_line += 1 if @str[@i] == '\n'
      end
    end
  end
end
  </pre></code>
</details>

**Comment by robacarp** [comment]
Sorry, I never concluded. I think this is fine to go in as is.

**Review by robacarp — APPROVED** [review]

**Comment by hugopl** [comment]
> This is the comparison I was thinking of:

Yeah, I knew you wanted a ips run, but I was too lazy to modify the existing code to be able to run both versions at same time 😅

**Pull request merged**
