### PR TITLE
Improve compatibility with Shopify liquid and make it way faster

### LINKED ISSUE #5: Improve expressions
- [ ] Add `contains` keyword ( http://shopify.github.io/liquid/basics/operators/ )
- [ ] Add support for Array into expressions
- [ ] Add square bracket [ ] notation to access an element

### PR DESCRIPTION
**Pull request by hugopl**
I need a liquid template engine in Crystal at work that is 100% compatible with the ruby engine, however I found that this shard not only lacks a lot of features but also supports a different dialect of the liquid language. Even so it still a very good base to start work on.

So... I started working on some patches to match this shard with the ruby version, here's a draft that's almost ready.

Since even after the move to amber this shards seems dead, I have no idea if the patches would be accepted... besides they have some breaking changes, but my plan is:

Port the [shopify liquid template integration tests](https://github.com/Shopify/liquid/tree/master/test/integration) (preferable in a automatic way) and run this shards against it.

Once it pass 100%, remove the draft tag from this PR and ask for review, if approved and merged, release under some major version, otherwise I release it under yet another fork and everybody still happy.

Any feedback on this PR is very welcome, this is the reason this PR is here in first place.

What's missing, what's done:

- [x] Port all ~shopify~ golden liquid tests.
- [x] Implement forloop variable (after the change to how expressions are evaluated this broke).
- [x] Implement drop.
- [ ] Implement empty drop.
- [x] Implement different error modes.
- [x] Implement blank literal.
- [ ] Implement empty literal (it need work against strings too),
- [x] Append/Prepend filters must accept non-string variables and coerce them.
- [x] Assign tag must accept filters.
- [x] Implement unless tag.
- [x] Make it faster.

This fixes #5 #6 #25 and #36

### CODE REVIEW

**Comment by crimson-knight** [comment]
Moving it into Amber was a precursor to me getting involved, we had Thanksgiving and I was traveling for work for a week. I'm on vacation until after the new year so I planned to do some work over the next few weeks.

I agree on aiming for 100% parity with the Shopify liquid tests, that'll bring the barrier of adoption way down

**Comment by hugopl** [comment]
This is ready for review...  there are things that I would like to remove from liquid.cr but I'm still in doubt, they are nice features, however not part of liquid.

- `!var` operator.
- `-var` operator.
- `pluralize` filter, or move it to a different shard, so liquid.cr keeps clean with zero dependencies.

Meanwhile I'm just adding fixes for incompatibilities I find here, like the patch about `prepend`/`append` filters that didn't coerce parameters to strings.

**Comment by hugopl** [comment]
Current status:
```
Finished in 32.98 milliseconds
1018 examples, 0 failures, 0 errors, 451 pending
```

**Comment by meatball133** [comment]
Hi!

I just want to let you know that these changes, would brick my current uses of the library, since I use this library since it can parse JSON::Any.

With these changes that wouldn't be possible, since the following error message is raised:

```
Error: expected argument #2 to 'Liquid::Context#set' to be (Array(Liquid::Any) | Bool | Float32 | Float64 | Hash(String, Liquid::Any) | Int32 | Int64 | Liquid::Drop | String | Time | Nil) or Liquid::Any, not JSON::Any
```

I was wondering if it is possible to add support for JSON::Any again since I really need that. 


Other than that do I think it is really good that you are working on making this library more feature rich.

**Comment by meatball133** [comment]
Also since I can't test with this new version but the old version (0.4.1) would indexing with a key into an array raise an error, in my opinion at least so should it return nil.

Btw along as JSON support is coming and if you want, I am up for helping you with this, although as I said, I need json otherwise I may aswell just find another solution or keep using the old version.

**Comment by hugopl** [comment]
> Hi!
> 
> I just want to let you know that these changes, would brick my current uses of the library, since I use this library since it can parse JSON::Any.

It's possible to add a overload to `'Liquid::Context#set` that receive a JSON::Any and maybe annotate it as deprecated.

Besides this API breakage that is easy to fix there are some behavior changes in liquid template itself to match the shopify ruby behavior, but these I would consider a bug fix rather than a API change.

**Comment by hugopl** [comment]
> Also since I can't test with this new version but the old version (0.4.1) would indexing with a key into an array raise an error, in my opinion at least so should it return nil.

I added back support for `Context.set(String, JSON::Any)`, you need to require `liquid/json` to access the API, does it work for you this way?

**Comment by hugopl** [comment]
Current status:
```
Finished in 24.3 milliseconds
975 examples, 0 failures, 0 errors, 434 pending
```

Most of the failing tests are very easy to fix, just minor tweaks in filters.... if someone want to try the steps are:

- Remove the test you want to fix from the file `spec/integration/golden_liquid.pending`
- Run the tests with `crystal spec`

To reduce the noise of pending tests use `SKIP_PENDING=1 crystal spec`

**Review by crimson-knight — APPROVED** [review]
Awesome job! I'll admit, a 100 file PR for a library I'm not super intimately familiar with was hard to read through.

However, you did an excellent job. I can see clear intent, good organization and the changes make sense.

I'll merge this into master so that the filter list is updated and I can hop in to help. We should also make a blog post about this on the amber framework site because it reaches around 600-1000 people per month, so that may bring more users and contributors.

**Comment by crimson-knight** [comment]
Before I merge this, I just want to ask that for other filter additions/enhancements, can we stick to a single PR per filter? If you tag me in them I'll see the notification faster and can usually same day review/merge. 

I'm also 1000x more responsive on Discord, but my email inbox gets flooded with spam so much it's hard to filter the garbage from the important stuff.

**Comment by hugopl** [comment]
Sorry for the large PR, I started with small PRs but while they were waiting for review I needed to do more stuff, then more stuff that depended on yet more stuff.... so as I saw not much response in the PRs I thought: _"Ok, I'll just push the commits in this branch that will be good for me to use and let it here if someone have interest."_

Now all liquid templates the customers of the company I'm working for wrote renders exactly like liquid ruby does, but as the golden tests show the customers seems to be using just the basic of liquid template powers.

So the next steps IMO are:

- Pass on more golden tests.
- Identify API breakage (like the JSON one in https://github.com/amberframework/liquid.cr/pull/69#issuecomment-1383181215) to try to minimize the headache when upgrading this library.
- Release with a nice non-patch version bump.

**Comment by hugopl** [comment]
image

**Comment by crimson-knight** [comment]
Yeah I think these changes make this a major release version

**Pull request merged**
